### ISSUE TITLE
change style / looks 

### ISSUE THREAD

**Issue by marc-portier** [ocean-sampling-day/ocean-sampling-day.github.io#2]
the merlot theme we are starting with is too different from the generated ro-crate-previews of the subpages

**Comment by marc-portier** [comment]
even the new style applied during meeting 2022-05-03 has some room for improvement
- should spill over to subsites
- should bring a recurring header/footer and feel of consistency
- also should link to our vliz-be-opsci space (to be created)

**Comment by kmexter** [comment]
Katrina can add text/content to the footer and a wee bit more blabla to the existing text, and can provide an OSD image. 
Just say when and where to do that.

**Comment by marc-portier** [comment]
strategy to introduce some conformity between the subsites and the main one

1. loading the css --> both could be referring to an agreed /css/main.css 
    * this should be provided by this parent-level-side and just included by the child-sites
    * if it is not there - 404 on css will just not load and hopefully the subsite has some internal way for proper default styling
    * note that the top level can still use existing themes and meaningful css names by using a css `@import` statement
2. further the subsite could be "inviting" the parent structure to inject header-footer content through that very same css
    * by introducing surrounding `<a href="/"><div class="ro-crate-preview-header"></div></a>` and  `<div class="ro-crate-preview-header"></div>` snippets 
    * these could be just leading to be ignored (visually not taking any space) if no-css or no-content is provided
    * the parent level css can simply inject the content to be displayed through rules like
    
``` css
.ro-crate-preview-header::before {
  content: '';
  background:url('«relative path from css to logo.png provided by parent project»') 
} 
.ro-crate-preview-header::after {
  content: "«name of the project»"
} 
```
